# Generated by Django 4.2.4 on 2023-08-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='business',
            table='business',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
